### ISSUE TITLE
ActiveLayers fails with new Leaflet versions

### ISSUE THREAD

**Issue by mpuputti** [vogdb/Leaflet.ActiveLayers#12]
Function `_recountLayers` accesses function `this._form.getElementsByTagName.`
With newer versions of Leaflet, this code fails, because Leaflet has changed `_form` to `_section.`
I think the change was in Leaflet version 1.4.0.

That is, line 108 in ActiveLayers.js should be changed from
`      inputs = this._form.getElementsByTagName('input'),`
to 
`      inputs = this._section.getElementsByTagName('input'),`

**Comment by vogdb** [comment]
Hello! Thank you for feedback. I don't have enough time currently. Can you make a PR please?

**Comment by mpuputti** [comment]
PR #14 created.
